LibUnicode: Hide the Unicode allocator override behind a feature
A future commit will make LibJS and LibRegex depend on LibUnicode's rust
module. The global allocator overrides will cause a compliation error:

    error: the `#[global_allocator]` in this crate conflicts with global
    allocator in: libunicode_rust

This hides the allocator override behind a feature flag that is enabled
for the standalone LibUnicode shared library.